ansible_host: psa.in.tum.de
ansible_port: 60202

host_name: vmpsateam02-02

network_interfaces:
  enp0s8:
    dhcp: false
    addresses:
      - 192.168.2.2/24
    routes:
      - to: 192.168.1.0/24
        via: 192.168.2.1
      - to: 192.168.3.0/24
        via: 192.168.2.1
      - to: 192.168.4.0/24
        via: 192.168.2.1
      - to: 192.168.5.0/24
        via: 192.168.2.1
      - to: 192.168.6.0/24
        via: 192.168.2.1
      - to: 192.168.7.0/24
        via: 192.168.2.1
      - to: 192.168.8.0/24
        via: 192.168.2.1
      - to: 192.168.9.0/24
        via: 192.168.2.1
      - to: 192.168.10.0/24
        via: 192.168.2.1

  enp0s3:
    dhcp: true

iptables:
  http_proxy_host: 131.159.0.2 # proxy.cit.tum.de
  http_proxy_port: 8080
  outgoing_explicit_allow:
    - 131.159.0.0/16 # FMI
    - 141.30.62.26 # ubuntu.mirror.tudos.de / de.archive.ubuntu.com
    - 185.125.190.39 # security.ubuntu.com
    - 192.168.2.0/24
