ansible_host: psa.in.tum.de
ansible_port: 60202

host_name: vmpsateam02-02

network_interfaces:
  enp0s8:
    dhcp: false
    addresses:
      - 192.168.2.2/24
    routes:
      - to: 192.168.1.0/24
        via: 192.168.2.1
      - to: 192.168.3.0/24
        via: 192.168.2.1
      - to: 192.168.4.0/24
        via: 192.168.2.1
      - to: 192.168.5.0/24
        via: 192.168.2.1
      - to: 192.168.6.0/24
        via: 192.168.2.1
      - to: 192.168.7.0/24
        via: 192.168.2.1
      - to: 192.168.8.0/24
        via: 192.168.2.1
      - to: 192.168.9.0/24
        via: 192.168.2.1
      - to: 192.168.10.0/24
        via: 192.168.2.1

  enp0s3:
    dhcp: true

iptables:
  outgoing_explicit_allow:
    - 131.159.0.0/16 # FMI
    - 192.168.2.0/24
    - de.archive.ubuntu.com
    - security.ubuntu.com
