- import_tasks: dependencies.yml
  tags:
    - ldap
    - ldap-dependencies

- import_tasks: config.yml
  tags:
    - ldap
    - ldap-config

- import_tasks: tls.yml
  tags:
    - ldap
    - ldap-tls

- import_tasks: users.yml
  tags:
    - ldap
    - ldap-users

