- import_tasks: disable-cloudinit.yml
  tags:
    - netplan
    - netplan-disable-cloudinit

- import_tasks: config.yml
  tags:
    - netplan
    - netplan-config

- import_tasks: apply.yml
  tags:
    - netplan
    - netplan-apply
